// Code generated by "stringer -type=CommentType"; DO NOT EDIT.

package testdata

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InlineComment-0]
	_ = x[BlockInlineComment-1]
	_ = x[BlockMultilineComment-2]
}

const _CommentType_name = "InlineCommentBlockInlineCommentBlockMultilineComment"

var _CommentType_index = [...]uint8{0, 13, 31, 52}

func (i CommentType) String() string {
	if i < 0 || i >= CommentType(len(_CommentType_index)-1) {
		return "CommentType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CommentType_name[_CommentType_index[i]:_CommentType_index[i+1]]
}
